---
# tasks file for dns-static
- name: generate file dns-static.rsc and load configuration
  template: src=dns-static.rsc.j2 dest=$HOME/mikrotik-ansible/roles/dns-static/files/tmp/{{inventory_hostname}}.rsc

- name: run .rsc script
  command:  bash -c "cat $HOME/mikrotik-ansible/roles/dns-static/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ssh_port}}"

- name: delete .rsc script on tmp
  file: path=$HOME/mikrotik-ansible/roles/dns-static/files/tmp/{{inventory_hostname}}.rsc state=absent
