---
# tasks file for ansible-user
- name: Generate .rsc to check and add user
  template: src=ansible-user.rsc.j2 dest=$HOME/mikrotik-ansible/roles/ansible-user/files/tmp/{{inventory_hostname}}.rsc

- name: Run .rsc script
  command: bash -c "cat $HOME/mikrotik-ansible/roles/ansible-user/files/tmp/{{inventory_hostname}}.rsc | sshpass -p "{{mikrotik_password}}" ssh {{mikrotik_login}}@{{inventory_hostname}} -p {{ssh_port}} -T -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1"

- name: Delete temp .rsc file
  file: path=$HOME/mikrotik-ansible/roles/ansible-user/files/tmp/{{inventory_hostname}}.rsc state=absent
