---
# tasks file for ip-address
- name: generate ipaddress.rsc and apply
  template: src=ipaddress.rsc.j2 dest=$HOME/mikrotik-ansible/roles/ip-address/files/tmp/{{inventory_hostname}}.rsc
- name: run ipaddress.rsc
  command: bash -c "cat $HOME/mikrotik-ansible/roles/ip-address/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ssh_port}}"
- name: delete file ipaddress.rsc
  file: path=$HOME/mikrotik-ansible/roles/ip-address/files/tmp/{{inventory_hostname}}.rsc state=absent
